server:
  port: 8093
  address: localhost


logging:
    level:
        root: debug
        org.springframework.web: debug
        org.apache.ibatis: debug
        com.happylifeplat.bonuspoint: debug
        com.happylifeplat.lottery: debug
        com.happylifeplat: debug
    path: "./logs"


