server:
  port: 8093
  address: 0.0.0.0


logging:
    level:
        root: error
        org.springframework.web: debug
        org.apache.ibatis: error
        com.happylifeplat.bonuspoint: debug
        com.happylifeplat.lottery: debug
        com.happylifeplat: debug
    path: "./logs"


