server:
  port: 8093
  address: 0.0.0.0


logging:
    level:
        root: error
        org.springframework.web: info
        org.apache.ibatis: info
        com.happylifeplat.bonuspoint: info
        com.happylifeplat.lottery: info
        com.happylifeplat: info
        com.ctrip.framework.apollo: debug
    path: "./logs"


